### ISSUE TITLE
generate_samples() code from gpt2 train.py -- InvalidArgumentError

### ISSUE THREAD

**Issue by radiodee1** [nshepperd/gpt-2#14]
I'm looking at a gpt2 tensorflow github repository. 

I would like to modify the code in the train.py file to fine tune gpt2. I want to create samples from the model with a paragraph of my own choosing as the context. For example, if I load my paragraph into the data_sampler, using Sample(), and then change the call to data_sampler.sample(1) to a number higher than 1 (5 for example) I get a error. 

            def generate_samples():
            print('Generating samples...')
            context_tokens = data_sampler.sample(5) ## <<--- change here!!
            all_text = []
            index = 0
            while index < args.sample_num:
                out = sess.run(
                    tf_sample,
                    feed_dict={context: args.batch_size * [context_tokens]})
                for i in range(min(args.sample_num - index, args.batch_size)):
                    text = enc.decode(out[i])
                    text = '======== SAMPLE {} ========\n{}\n'.format(
                        index + 1, text)
                    all_text.append(text)
                    index += 1
            print(text)
            maketree(os.path.join(SAMPLE_DIR, args.run_name))
            with open(
                    os.path.join(SAMPLE_DIR, args.run_name,
                                 'samples-{}').format(counter), 'w') as fp:
                fp.write('\n'.join(all_text))
                

I get the following error.

                
    InvalidArgumentError (see above for traceback): indices[0,0] = 1024 is not in [0, 1024)
    	 [[node sample_sequence/while/model/GatherV2_1 (defined at ../model/tf_gpt2/src/model.py:157) ]]
    	 
The full error is below. NOTE: I have copied the original train.py file and renamed it tf_gpt2_train_babi.py. My ultimate goal is to try the babi synthetic data set with gpt2, which explains the name.

Traceback (most recent call last):
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
	 [[{{node sample_sequence/while/model/GatherV2_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tf_gpt2_train_babi.py", line 370, in <module>
    main()
  File "./tf_gpt2_train_babi.py", line 334, in main
    generate_samples()
  File "./tf_gpt2_train_babi.py", line 268, in generate_samples
    feed_dict={context: args.batch_size * [context_tokens]})
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
	 [[node sample_sequence/while/model/GatherV2_1 (defined at ../model/tf_gpt2/src/model.py:157) ]]

Caused by op 'sample_sequence/while/model/GatherV2_1', defined at:
  File "./tf_gpt2_train_babi.py", line 370, in <module>
    main()
  File "./tf_gpt2_train_babi.py", line 159, in main
    top_k=40)
  File "../model/tf_gpt2/src/sample.py", line 76, in sample_sequence
    back_prop=False,
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3022, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3525, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "../model/tf_gpt2/src/sample.py", line 50, in body
    next_outputs = step(hparams, prev[:, tf.newaxis], past=past)
  File "../model/tf_gpt2/src/sample.py", line 33, in step
    lm_output = model.model(hparams=hparams, X=tokens, past=past, reuse=tf.AUTO_REUSE)
  File "../model/tf_gpt2/src/model.py", line 157, in model
    h = tf.gather(wte, X) + tf.gather(wpe, positions_for(X, past_length))
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 3273, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3748, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/dave/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[0,0] = 1024 is not in [0, 1024)
	 [[node sample_sequence/while/model/GatherV2_1 (defined at ../model/tf_gpt2/src/model.py:157) ]]

**Comment by lostmsu** [comment]
@radiodee1 I just faced the same error, but only when sampling on CPU (with CUDA it does not occur). Were you able to figure it out?
