### ISSUE TITLE
Zero Division Error

### ISSUE THREAD

**Issue by Chris-Rigas** [nshepperd/gpt-2#18]
I'm the following error:

Traceback (most recent call last):
  File "./train.py", line 293, in <module>
    main()
  File "./train.py", line 271, in main
    feed_dict={context: sample_batch()})
  File "./train.py", line 247, in sample_batch
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "./train.py", line 247, in <listcomp>
    return [data_sampler.sample(1024) for _ in range(args.batch_size)]
  File "/Users/crigas/gpt-2/src/load_dataset.py", line 74, in sample
    self.chunks
ZeroDivisionError: integer division or modulo by zero

Any help would be appreciated!

**Comment by DaltonSchutte** [comment]
I'm seeing the same error when I try to fine-tune the model. After digging through the code, I wonder if it has to do with how our dataset is being broken down. Likely the error is originating from

`assert length < self.total_size // len(self.chunks)`

Which implies that self.chunks has length zero and is empty. In train.py the variable `chunks` that is given to the `Sampler` object is created with `load_dataset` which returns a list of tokens. So, we can conclude that nothing is being appended to the function variable `token_chunks` in `load_dataset`. However, at that point there seem to be a couple of different potential causes.

**Comment by iedmrc** [comment]
I faced the same problem. The issue was the wrong file path. If you provide a file path that doesn't include any proper file, the script will continue to run but the process will conclude with zero tokens. So make sure that you have proper file(s) in the path you provided.
