### ISSUE TITLE
Apologies, but HELP

### ISSUE THREAD

**Issue by OdincoGaming** [nshepperd/gpt-2#32]
when I try to encode a custom data set I receive these errors, I am relatively new to python and am unable to debug this myself. Ive been at it for two days now and I still cant figure it out. please help :(

`(base) C:\Users\ThisPC\Downloads\Python\AI\gpt-2-finetuning>python encode.py WordBank.txt WordBank.npz
Traceback (most recent call last):
  File "encode.py", line 31, in <module>
    main()
  File "encode.py", line 23, in main
    enc = encoder.get_encoder(args.model_name)
  File "C:\Users\ThisPC\Downloads\Python\AI\gpt-2-finetuning\encoder.py", line 110, in get_encoder
    encoder = json.load(f)
  File "C:\Users\ThisPC\Anaconda3\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\ThisPC\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ThisPC\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ThisPC\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by OdincoGaming** [comment]
am receiving unresolved import errors in the encode.py file on

import encoder
from load_dataset import load_dataset

**Comment by HandsomeDevilv112** [comment]
just per chance, do you happen to have anaconda 3 installed?

**Comment by mzjuin** [comment]
> when I try to encode a custom data set I receive these errors, I am relatively new to python and am unable to debug this myself. Ive been at it for two days now and I still cant figure it out. please help :(
> 
> (base) C:\Users\ThisPC\Downloads\Python\AI\gpt-2-finetuning>python encode.py WordBank.txt WordBank.npz
> Traceback (most recent call last):
> File "encode.py", line 31, in
> main()
> File "encode.py", line 23, in main
> enc = encoder.get_encoder(args.model_name)
> File "C:\Users\ThisPC\Downloads\Python\AI\gpt-2-finetuning\encoder.py", line 110, in get_encoder
> encoder = json.load(f)
> File "C:\Users\ThisPC\Anaconda3\lib\json__init__.py", line 296, in load
> parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
> File "C:\Users\ThisPC\Anaconda3\lib\json__init__.py", line 348, in loads
> return _default_decoder.decode(s)
> File "C:\Users\ThisPC\Anaconda3\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "C:\Users\ThisPC\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I believe your json file is incorrectly formatted. check again in your json file with proper editor like vscode(json extension) to see where went wrong.

**Comment by OdincoGaming** [comment]
> 
> 
> just per chance, do you happen to have anaconda 3 installed?

I do, why?

**Comment by HandsomeDevilv112** [comment]
it might be trying to use python 2 instead of python 3, try
python3 encode.py WordBank.txt WordBank.npz
(note: I also have no idea what I'm doing)
