### ISSUE TITLE
OOM With Gradient Checkpointing on 1080 Ti

### ISSUE THREAD

**Issue by 9of9** [nshepperd/gpt-2#5]
Attempting to seed 345M with a pre-encoded dataset - I have a 1080 Ti, but even after checking that memory saving gradients is enabled, I run into an OOM exception after a few seconds of training:

```
2019-05-12 14:33:35.460258: I tensorflow/core/common_runtime/bfc_allocator.cc:641] 1 Chunks of size 230633472 totalling 219.95MiB
2019-05-12 14:33:35.463612: I tensorflow/core/common_runtime/bfc_allocator.cc:645] Sum Total of in-use chunks: 8.58GiB
2019-05-12 14:33:35.467832: I tensorflow/core/common_runtime/bfc_allocator.cc:647] Stats:
Limit:                  9218918974
InUse:                  9217796864
MaxInUse:               9217796864
NumAllocs:                    3470
MaxAllocSize:            329412864

2019-05-12 14:33:35.475291: W tensorflow/core/common_runtime/bfc_allocator.cc:271] ****************************************************************************************************
2019-05-12 14:33:35.482129: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at cast_op.cc:109 : Resource exhausted: OOM when allocating tensor with shape[1,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model/h23/attn/truediv_1}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 268, in <module>
    main()
  File "train.py", line 246, in main
    feed_dict={context: sample_batch()})
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node model/h23/attn/truediv_1 (defined at e:\NeuralNets\gpt-2-seeded\src\memory_saving_gradients.py:204) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'model/h23/attn/truediv_1', defined at:
  File "train.py", line 268, in <module>
    main()
  File "train.py", line 116, in main
    opt_grads = memory_saving_gradients.gradients(loss, train_vars)
  File "e:\NeuralNets\gpt-2-seeded\src\memory_saving_gradients.py", line 204, in gradients
    copied_sgv, info = ge.copy_with_input_replacements(ge.sgv(ops_to_copy), {})
  File "E:\Anaconda\lib\site-packages\tensorflow\contrib\graph_editor\transform.py", line 673, in copy_with_input_replacements
    sgv, dst_graph, dst_scope, src_scope, reuse_dst_scope=reuse_dst_scope)
  File "E:\Anaconda\lib\site-packages\tensorflow\contrib\graph_editor\transform.py", line 453, in __call__
    self._copy_ops(info)
  File "E:\Anaconda\lib\site-packages\tensorflow\contrib\graph_editor\transform.py", line 467, in _copy_ops
    op_, op_outputs_ = self.transform_op_handler(info, op, new_inputs)
  File "E:\Anaconda\lib\site-packages\tensorflow\contrib\graph_editor\transform.py", line 177, in copy_op_handler
    [], input_types_, None, op_def_)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,16,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node model/h23/attn/truediv_1 (defined at e:\NeuralNets\gpt-2-seeded\src\memory_saving_gradients.py:204) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

What am I missing? Is there any way to reduce memory usage even further?

**Comment by 9of9** [comment]
Had some luck in the end, when calling memory_saving_gradients.gradients(), setting checkpoints='speed' rather than the default checkpoints='collection'.

**Comment by pdeepthi97** [comment]
Getting the same OOM error despite using memory saving gradients and SGD optimizer on my RPI. How was this fixed?
